
export const GENERATE_PASSWORD_START = 'HOME:GENERATE_PASSWORD_START'
export const GENERATE_PASSWORD_SUCCESS = 'HOME:GENERATE_PASSWORD_SUCCESS'
export const GENERATE_PASSWORD_ERROR = 'HOME:GENERATE_PASSWORD_ERROR'
export const UPDATE_PASSWORD = 'HOME:UPDATE_PASSWORD'
